### ISSUE TITLE
Error executing Lua callback Cannot find color 'CurSearch'

### ISSUE THREAD

**Issue by aspersieman** [Dax89/IDE.nvim#2]
Good day

I've recently installed ide.nvim and I'm getting some errors when running :IdeProjectCreate 

I'm getting the following error:
```
Error executing Lua callback: ...pack/packer/start/ide.nvim/lua/ide/ui/dialogs/dialog.lua:211: Cannot find color 'CurSearch'
stack traceback:                                                                                                                                                                    
        [C]: in function 'error'
        ...pack/packer/start/ide.nvim/lua/ide/ui/dialogs/dialog.lua:211: in function 'hl'
        ...pack/packer/start/ide.nvim/lua/ide/ui/dialogs/dialog.lua:248: in function 'cb'
        ...te/pack/packer/start/ide.nvim/lua/ide/ui/base/buffer.lua:140: in function 'commit'
        ...pack/packer/start/ide.nvim/lua/ide/ui/dialogs/dialog.lua:240: in function 'render'
        ...te/pack/packer/start/ide.nvim/lua/ide/ui/base/buffer.lua:44: in function 'refresh'
        ...te/pack/packer/start/ide.nvim/lua/ide/ui/base/window.lua:45: in function 'show'
        ...pack/packer/start/ide.nvim/lua/ide/ui/dialogs/dialog.lua:94: in function 'popup'
        ...re/nvim/site/pack/packer/start/ide.nvim/lua/ide/init.lua:130: in function 'project_create'
        ...re/nvim/site/pack/packer/start/ide.nvim/lua/ide/init.lua:191: in function <...re/nvim/site/pack/packer/start/ide.nvim/lua/ide/init.lua:190>
```

Details:

1. `nvim --version`:
```
NVIM v0.8.0-1210-gd367ed9b2
Build type: Release
LuaJIT 2.1.0-beta3
Compiled by runner@fv-az505-656

Features: +acl +iconv +tui
See ":help feature-compile"

   system vimrc file: "$VIM/sysinit.vim"
  fall-back for $VIM: "/share/nvim"

Run :checkhealth for more info
```
2. `lsb_release -a`
```
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 11 (bullseye)
Release:	11
Codename:	bullseye
```
3. Terminal: gnome-terminal

Steps to reproduce:

- Install using packer as directed on readme
- Run :IdeProjectCreate

**Comment by Dax89** [comment]
It seems that the color group `CurSearch` is not found, may I know which color scheme are you using?

**Comment by LoneExile** [comment]
I got this error message too with [tokyonight.nvim](https://github.com/folke/tokyonight.nvim)

**Comment by Dax89** [comment]
@LoneExile: I can reproduce the issue with tokyonight, thanks!

**Comment by Dax89** [comment]
This commit https://github.com/Dax89/ide.nvim/commit/3aacb6d27943c03bea53c826ed32496f730a377c changes the UI's primary color from `CurSearch` to `Cursor` and it looks like it works with tokyo night too.

**Comment by NoahTheDuke** [comment]
lol I get this for `Cursor`, which is definitely defined in my [colorscheme](https://github.com/Mofiqul/dracula.nvim/blob/0b4f6e009867027caddc1f28a81d8a7da6a2b277/lua/dracula/groups.lua#L73).

**Comment by Dax89** [comment]
The problem is that `nvim_get_hl_by_name` doesn't always return the real RGB representation of a specific color group, I have added a workaround if `reverse` flag is set (like dracula color scheme for `Cursor` group) and I set the returned highlighting entirely.

Check if it works now!

**Comment by NoahTheDuke** [comment]
That fixed it, thank you!
